name: pdf_render_platform_interface
description: Platform interface for the pdf_render plugin.
homepage: https://github.com/espresso3389/flutter_pdf_render

# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 1.0.0-dev

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4
  plugin_platform_interface: ^1.1.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.20.0 <2.0.0"

